# application.yml
spring:
  profiles:
    active: local # 디폴트 환경


# 서버 개발자 테스트 환경
#
#  java -Dspring.profiles.active=test -jar [jar파일명].jar
#  nohup java -jar [jar파일명].jar --spring.profiles.active=test &


# 클라이언트 개발자 테스트 배포 환경
#
#  java -Dspring.profiles.active=release -jar [jar파일명].jar
#  nohup java -jar [jar파일명].jar --spring.profiles.active=release &
