server:
  port: 9404

spring:
  profiles:
    active: "test"
  application:
    name: demo
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
      # create, update, create-drop, none 등의 옵션이 있습니다.
      # create: 기존테이블 삭제 후 다시 생성
      # update: 변경된 부분만 반영
      # create-drop: create와 같으나 종료 시점에 테이블 DROP
      # none: 사용하지 않음
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # DDl 생성 시 데이터베이스 고유의 기능 사용여부
    generate-ddl: false
    # 실행되는 쿼리문 보여주기 여부
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    platform: mysql
    url: jdbc:mysql://database-1.cszqh4k3n47k.ap-northeast-2.rds.amazonaws.com:3306/PR2_shine_divi
    username: admin
    password: shine1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl

cloud:
  aws:
    credentials:
      accessKey: AKIAZRSXSWVMQKHI6QOE
      secretKey: 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
    s3:
      bucket: grip-image-directory
    region:
      static: ap-northeast-2
    stack:
      auto: false