spring:
  h2:
    console:
      enabled: true
  profiles:
    active: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:userdb;DB_CLOSE_DELAY=-1
    username: sa
    password:

cloud:
  aws:
    credentials:
      accessKey: AKIAZRSXSWVMQKHI6QOE
      secretKey: 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
    s3:
      bucket: grip-image-directory
    region:
      static: ap-northeast-2
    stack:
      auto: false